import type { GameAssetDefinition } from "./types";
import {
  blockyCharacter,
  defineAsset,
  modularFantasy,
  natureProp,
  natureTile,
  natureTree,
  castleModular,
  castleProp,
  retroFantasyModular,
  retroFantasyProp,
  pirateModular,
  pirateProp,
  propFantasy,
  roadFantasy,
  survivalBuilding,
  survivalProp,
  withOverrides,
} from "./catalog-builders";

function defineObelisk(): GameAssetDefinition {
  return defineAsset("nature.obelisk", {
    kit: "nature",
    model: "statue_obelisk",
    role: "building",
    district: "core",
    uniformScale: 3.2,
    pivotMode: "ground-center",
    pivotOffset: [0, 0, 0],
    castsShadow: true,
    receivesShadow: true,
    instanceable: false,
  });
}

/** Curated Kenney GLBs for the redesigned clan village. */
export const CATALOG_ENTRIES: GameAssetDefinition[] = [
  // —— Town Hall modular (Fantasy) ——
  modularFantasy("townHall.wallStone", "wall-block"),
  modularFantasy("townHall.wallStoneHalf", "wall-block-half"),
  modularFantasy("townHall.wallCorner", "wall-corner-detail"),
  modularFantasy("townHall.wallDoor", "wall-door"),
  modularFantasy("townHall.wallArch", "wall-arch"),
  modularFantasy("townHall.wallDoorWide", "wall-doorway-square-wide"),
  modularFantasy("townHall.wallCurved", "wall-curved"),
  modularFantasy("townHall.wallRounded", "wall-rounded"),
  modularFantasy("townHall.wallWoodRounded", "wall-wood-rounded"),
  modularFantasy("townHall.wallWindow", "wall-window-stone"),
  modularFantasy("townHall.wallWood", "wall-wood"),
  modularFantasy("townHall.wallWoodHalf", "wall-wood-half"),
  modularFantasy("townHall.wallWoodCorner", "wall-wood-corner"),
  modularFantasy("townHall.wallWoodDoor", "wall-wood-door"),
  modularFantasy("townHall.wallWoodWindow", "wall-wood-window-shutters"),
  modularFantasy("townHall.wallWoodWindowRound", "wall-wood-window-round"),
  modularFantasy("townHall.wallWoodDetail", "wall-wood-detail-cross"),
  modularFantasy("townHall.wallWoodDetailH", "wall-wood-detail-horizontal"),
  modularFantasy("townHall.roof", "roof"),
  modularFantasy("townHall.roofLeft", "roof-left"),
  modularFantasy("townHall.roofRight", "roof-right"),
  modularFantasy("townHall.roofGable", "roof-gable"),
  modularFantasy("townHall.roofGableDetail", "roof-gable-detail"),
  modularFantasy("townHall.roofGableEnd", "roof-gable-end"),
  modularFantasy("townHall.roofGableTop", "roof-gable-top"),
  modularFantasy("townHall.roofWindow", "roof-window"),
  modularFantasy("townHall.roofHigh", "roof-high"),
  modularFantasy("townHall.roofHighLeft", "roof-high-left"),
  modularFantasy("townHall.roofHighRight", "roof-high-right"),
  modularFantasy("townHall.roofHighGable", "roof-high-gable"),
  modularFantasy("townHall.roofHighGableDetail", "roof-high-gable-detail"),
  modularFantasy("townHall.roofHighPoint", "roof-high-point"),
  modularFantasy("townHall.roofPoint", "roof-point"),
  modularFantasy("townHall.roofHighWindow", "roof-high-window"),
  modularFantasy("townHall.stairsStone", "stairs-stone"),
  modularFantasy("townHall.stairsWide", "stairs-wide-stone"),
  modularFantasy("townHall.stairsWood", "stairs-wood"),
  modularFantasy("townHall.stairsWoodHandrail", "stairs-wood-handrail"),
  modularFantasy("townHall.balconyWall", "balcony-wall"),
  modularFantasy("townHall.balconyFence", "balcony-wall-fence"),
  modularFantasy("townHall.overhang", "overhang"),
  modularFantasy("townHall.pillarStone", "pillar-stone"),
  modularFantasy("townHall.pillarWood", "pillar-wood"),
  propFantasy("townHall.chimney", "chimney"),
  propFantasy("townHall.chimneyBase", "chimney-base"),
  propFantasy("townHall.chimneyTop", "chimney-top"),
  modularFantasy("townHall.stairsWideHandrail", "stairs-wide-stone-handrail"),
  propFantasy("village.bannerRed", "banner-red"),
  propFantasy("village.bannerGreen", "banner-green"),
  propFantasy("village.lantern", "lantern"),
  propFantasy("village.fountain", "fountain-round-detail"),
  propFantasy("village.fountainSquare", "fountain-square-detail"),
  modularFantasy("village.stallRed", "stall-red", "village"),
  modularFantasy("village.stallGreen", "stall-green", "village"),
  propFantasy("village.stallBench", "stall-bench"),
  propFantasy("village.cart", "cart-high"),
  propFantasy("village.stallStool", "stall-stool"),
  propFantasy("village.cartLow", "cart"),
  roadFantasy("village.road", "road"),
  roadFantasy("village.roadBend", "road-bend"),
  roadFantasy("village.roadCorner", "road-corner"),
  roadFantasy("village.roadCornerInner", "road-corner-inner"),
  roadFantasy("village.roadCurb", "road-curb"),
  roadFantasy("village.roadCurbEnd", "road-curb-end"),
  roadFantasy("village.roadEdge", "road-edge"),
  roadFantasy("village.roadEdgeSlope", "road-edge-slope"),
  roadFantasy("village.roadSlope", "road-slope"),
  propFantasy("village.fence", "fence"),
  propFantasy("village.fenceCurved", "fence-curved"),
  propFantasy("village.fenceGate", "fence-gate"),
  propFantasy("village.fenceBroken", "fence-broken"),
  propFantasy("village.hedge", "hedge"),
  propFantasy("village.hedgeCurved", "hedge-curved"),
  propFantasy("village.hedgeGate", "hedge-gate"),
  propFantasy("village.fountainRound", "fountain-round"),
  propFantasy("village.hedgeLarge", "hedge-large"),
  propFantasy("village.hedgeLargeGate", "hedge-large-gate"),
  modularFantasy("village.stall", "stall", "village"),
  modularFantasy("village.planks", "planks", "village"),
  withOverrides(propFantasy("village.rockLarge", "rock-large", "forest"), {
    instanceable: true,
    uniformScale: 1.2,
  }),
  withOverrides(propFantasy("village.rockSmall", "rock-small", "forest"), {
    instanceable: true,
    uniformScale: 1,
  }),
  withOverrides(propFantasy("village.rockWide", "rock-wide", "forest"), {
    instanceable: true,
    uniformScale: 1.1,
  }),
  withOverrides(propFantasy("village.tree", "tree", "forest"), {
    instanceable: true,
    uniformScale: 2.9,
  }),
  withOverrides(propFantasy("village.treeHigh", "tree-high", "forest"), {
    instanceable: true,
    uniformScale: 2.9,
  }),
  withOverrides(propFantasy("village.treeCrooked", "tree-crooked", "forest"), {
    instanceable: true,
    uniformScale: 2.9,
  }),
  withOverrides(modularFantasy("village.windmill", "windmill", "village"), {
    pivotMode: "ground-center",
  }),
  withOverrides(propFantasy("village.windmillBlade", "blade"), {
    pivotMode: "preserve-origin",
  }),
  withOverrides(modularFantasy("village.watermill", "watermill-wide", "river"), {
    pivotMode: "ground-center",
  }),
  propFantasy("village.waterWheel", "wheel"),

  // —— Nature terrain & water ——
  natureTile("nature.platformGrass", "platform_grass"),
  natureTile("nature.platformBeach", "platform_beach"),
  natureTile("nature.platformStone", "platform_stone"),
  natureTile("nature.groundGrass", "ground_grass"),
  natureTile("nature.pathStraight", "ground_pathStraight"),
  natureTile("nature.pathBend", "ground_pathBend"),
  natureTile("nature.pathCorner", "ground_pathCorner"),
  natureTile("nature.pathCornerSmall", "ground_pathCornerSmall"),
  natureTile("nature.pathCross", "ground_pathCross"),
  natureTile("nature.pathSplit", "ground_pathSplit"),
  natureTile("nature.pathEnd", "ground_pathEnd"),
  natureTile("nature.pathEndClosed", "ground_pathEndClosed"),
  natureTile("nature.pathTile", "ground_pathTile"),
  natureTile("nature.pathRocks", "ground_pathRocks"),
  natureTile("nature.pathSide", "ground_pathSide"),
  natureTile("nature.pathSideOpen", "ground_pathSideOpen"),
  natureTile("nature.pathStone", "path_stone"),
  natureTile("nature.pathStoneCorner", "path_stoneCorner"),
  natureTile("nature.pathStoneEnd", "path_stoneEnd"),
  natureTile("nature.pathWood", "path_wood"),
  natureTile("nature.pathWoodCorner", "path_woodCorner"),
  natureTile("nature.pathWoodEnd", "path_woodEnd"),
  natureTile("nature.riverStraight", "ground_riverStraight", "water", "river"),
  natureTile("nature.riverBend", "ground_riverBend", "water", "river"),
  natureTile("nature.riverBendBank", "ground_riverBendBank", "water", "river"),
  natureTile("nature.riverCorner", "ground_riverCorner", "water", "river"),
  natureTile("nature.riverCornerSmall", "ground_riverCornerSmall", "water", "river"),
  natureTile("nature.riverCross", "ground_riverCross", "water", "river"),
  natureTile("nature.riverSplit", "ground_riverSplit", "water", "river"),
  natureTile("nature.riverEnd", "ground_riverEnd", "water", "river"),
  natureTile("nature.riverEndClosed", "ground_riverEndClosed", "water", "river"),
  natureTile("nature.riverTile", "ground_riverTile", "water", "river"),
  natureTile("nature.riverRocks", "ground_riverRocks", "water", "river"),
  natureTile("nature.riverSide", "ground_riverSide", "water", "river"),
  natureTile("nature.riverSideOpen", "ground_riverSideOpen", "water", "river"),
  natureTile("nature.riverOpen", "ground_riverOpen", "water", "river"),
  natureTile("nature.bridgeWood", "bridge_wood"),
  natureTile("nature.bridgeWoodNarrow", "bridge_woodNarrow"),
  natureTile("nature.bridgeWoodRound", "bridge_woodRound"),
  natureTile("nature.bridgeStone", "bridge_stone"),
  natureTile("nature.cliffBlock", "cliff_block_rock"),
  natureTile("nature.cliffBlockHalf", "cliff_blockHalf_rock"),
  natureTile("nature.cliffBlockQuarter", "cliff_blockQuarter_rock"),
  natureTile("nature.cliffBlockDiagonal", "cliff_blockDiagonal_rock"),
  natureTile("nature.cliffBlockSlope", "cliff_blockSlope_rock"),
  natureTile("nature.cliffCorner", "cliff_corner_rock"),
  natureTile("nature.cliffCornerLarge", "cliff_cornerLarge_rock"),
  natureTile("nature.cliffCornerInner", "cliff_cornerInner_rock"),
  natureTile("nature.cliffDiagonal", "cliff_diagonal_rock"),
  natureTile("nature.cliffHalf", "cliff_half_rock"),
  natureTile("nature.cliffLarge", "cliff_large_rock"),
  natureTile("nature.cliffSteps", "cliff_steps_rock"),
  natureTile("nature.cliffTop", "cliff_top_rock"),
  natureTile("nature.cliffTopDiagonal", "cliff_topDiagonal_rock"),
  natureTile("nature.waterfall", "cliff_waterfall_rock", "water", "river"),
  natureTile("nature.waterfallTop", "cliff_waterfallTop_rock", "water", "river"),
  natureTree("nature.pineTallA", "tree_pineTallA_detailed", false),
  natureTree("nature.pineTallB", "tree_pineTallB_detailed", false),
  natureTree("nature.pineTallC", "tree_pineTallC_detailed", false),
  natureTree("nature.pineTallD", "tree_pineTallD_detailed", false),
  natureTree("nature.pineDefaultA", "tree_pineDefaultA"),
  natureTree("nature.pineDefaultB", "tree_pineDefaultB"),
  natureTree("nature.pineRoundA", "tree_pineRoundA"),
  natureTree("nature.pineRoundB", "tree_pineRoundB"),
  natureTree("nature.pineRoundC", "tree_pineRoundC"),
  natureTree("nature.pineRoundD", "tree_pineRoundD"),
  natureTree("nature.pineSmallA", "tree_pineSmallA"),
  natureTree("nature.pineSmallB", "tree_pineSmallB"),
  natureTree("nature.pineSmallC", "tree_pineSmallC"),
  natureTree("nature.pineSmallD", "tree_pineSmallD"),
  natureTree("nature.oak", "tree_oak"),
  natureTree("nature.treeFat", "tree_fat"),
  natureTree("nature.treeDetailed", "tree_detailed"),
  natureTree("nature.treeDefault", "tree_default", false),
  natureTree("nature.treeSimple", "tree_simple"),
  natureTree("nature.treeBlocks", "tree_blocks"),
  natureTree("nature.treeTall", "tree_tall", false),
  natureTree("nature.treeThin", "tree_thin", false),
  natureProp("nature.bush", "plant_bushDetailed"),
  natureProp("nature.bushLarge", "plant_bushLarge", "forest", 2.4),
  natureProp("nature.bushSmall", "plant_bushSmall", "forest", 2),
  natureProp("nature.grass", "grass", "village", 1.8),
  natureProp("nature.grassLarge", "grass_large", "village", 2),
  natureProp("nature.flowerPurple", "flower_purpleA"),
  natureProp("nature.flowerRed", "flower_redA"),
  natureProp("nature.flowerYellow", "flower_yellowA"),
  natureProp("nature.mushrooms", "mushroom_redGroup"),
  natureProp("nature.mushroomTan", "mushroom_tanGroup"),
  natureProp("nature.rockLarge", "rock_largeA", "village", 2.8),
  natureProp("nature.rockLargeB", "rock_largeB", "village", 2.6),
  natureProp("nature.rockLargeC", "rock_largeC", "village", 2.6),
  natureProp("nature.rockLargeD", "rock_largeD", "village", 2.6),
  natureProp("nature.rockLargeE", "rock_largeE", "village", 2.6),
  natureProp("nature.rockLargeF", "rock_largeF", "village", 2.6),
  natureProp("nature.rockTallA", "rock_tallA", "village", 2.4),
  natureProp("nature.rockTallB", "rock_tallB", "village", 2.4),
  natureProp("nature.rockTallC", "rock_tallC", "village", 2.4),
  natureProp("nature.rockTallD", "rock_tallD", "village", 2.4),
  natureProp("nature.rockTallE", "rock_tallE", "village", 2.4),
  natureProp("nature.rockTallF", "rock_tallF", "village", 2.4),
  natureProp("nature.rockTallG", "rock_tallG", "village", 2.4),
  natureProp("nature.rockTallH", "rock_tallH", "village", 2.4),
  natureProp("nature.rockTallI", "rock_tallI", "village", 2.4),
  natureProp("nature.rockTallJ", "rock_tallJ", "village", 2.4),
  natureProp("nature.stoneLargeA", "stone_largeA", "village", 2.5),
  natureProp("nature.stoneLargeB", "stone_largeB", "village", 2.5),
  natureProp("nature.stoneLargeC", "stone_largeC", "village", 2.5),
  natureProp("nature.stoneLargeD", "stone_largeD", "village", 2.5),
  natureProp("nature.stoneLargeE", "stone_largeE", "village", 2.5),
  natureProp("nature.stoneLargeF", "stone_largeF", "village", 2.5),
  natureProp("nature.rockSmall", "rock_smallB"),
  natureProp("nature.rockSmallC", "rock_smallC"),
  natureProp("nature.lily", "lily_large", "river", 2),
  natureProp("nature.lilySmall", "lily_small", "river", 1.6),
  natureProp("nature.log", "log_large"),
  natureProp("nature.logStack", "log_stack", "forest", 2.2),
  natureProp("nature.stump", "stump_old"),
  natureProp("nature.crops", "crops_wheatStageB", "village", 2.5),
  natureProp("nature.cropsCorn", "crops_cornStageC", "village", 2.5),
  natureTile("nature.cropRows", "crops_dirtDoubleRow"),
  defineObelisk(),
  natureProp("nature.ring", "statue_ring", "core", 3),

  // —— Pirate harbor ——
  withOverrides(pirateModular("harbor.dock", "structure-platform-dock", "harbor", "terrain"), {
    pivotMode: "ground-center",
    uniformScale: 2.2,
  }),
  withOverrides(pirateModular("harbor.dockSmall", "structure-platform-dock-small", "harbor", "terrain"), {
    pivotMode: "ground-center",
    uniformScale: 2.2,
  }),
  withOverrides(pirateModular("harbor.platform", "structure-platform", "harbor", "terrain"), {
    pivotMode: "ground-center",
    uniformScale: 2,
  }),
  pirateProp("harbor.platformPlanks", "platform-planks", "harbor", 2),
  withOverrides(pirateProp("harbor.shipLarge", "ship-large", "harbor", 0.55), {
    approximateHeight: 10,
    footprint: [7, 14] as const,
  }),
  withOverrides(pirateProp("harbor.shipMedium", "ship-medium", "harbor", 0.6), {
    footprint: [5, 10] as const,
  }),
  withOverrides(pirateProp("harbor.shipSmall", "ship-small", "harbor", 0.65), {
    footprint: [4, 7] as const,
  }),
  pirateProp("harbor.rowboat", "boat-row-small", "harbor", 1.2),
  pirateProp("harbor.rowboatLarge", "boat-row-large", "harbor", 1.1),
  pirateModular("harbor.towerBaseDoor", "tower-base-door"),
  pirateModular("harbor.towerMiddleWindows", "tower-middle-windows"),
  pirateModular("harbor.towerTop", "tower-top"),
  pirateModular("harbor.towerRoof", "tower-roof"),
  pirateModular("harbor.towerWatch", "tower-watch", "harbor"),
  pirateModular("harbor.towerCompleteSmall", "tower-complete-small", "harbor"),
  withOverrides(pirateModular("harbor.towerCompleteLarge", "tower-complete-large", "harbor"), {
    pivotMode: "ground-center",
  }),
  pirateProp("harbor.flag", "flag-high-pennant"),
  pirateProp("harbor.flagHigh", "flag-high", "harbor", 1),
  pirateProp("harbor.flagPennant", "flag-pennant", "harbor", 1),
  pirateProp("harbor.crate", "crate"),
  pirateProp("harbor.crateBottles", "crate-bottles"),
  pirateProp("harbor.barrel", "barrel"),
  pirateProp("harbor.chest", "chest"),
  pirateProp("harbor.cannon", "cannon", "harbor", 1.2),
  pirateModular("harbor.castleGate", "castle-gate"),
  pirateModular("harbor.castleWall", "castle-wall"),
  pirateModular("harbor.castleDoor", "castle-door"),
  pirateModular("harbor.castleWindow", "castle-window"),
  pirateProp("harbor.palmBend", "palm-bend", "harbor", 2.5),
  pirateProp("harbor.palmStraight", "palm-straight", "harbor", 2.5),
  pirateProp("harbor.palmDetailed", "palm-detailed-bend", "harbor", 2.5),
  pirateProp("harbor.patchSand", "patch-sand", "harbor", 2.2),
  pirateProp("harbor.patchSandFoliage", "patch-sand-foliage", "harbor", 2.2),
  pirateProp("harbor.rocksSandA", "rocks-sand-a", "harbor", 2),
  pirateProp("harbor.rocksSandB", "rocks-sand-b", "harbor", 2),
  pirateProp("harbor.rocksSandC", "rocks-sand-c", "harbor", 2),
  pirateProp("harbor.mast", "mast", "harbor", 1.5),
  pirateProp("harbor.mastRopes", "mast-ropes", "harbor", 1.5),

  // —— Survival workshop ——
  survivalBuilding("workshop.structure", "structure"),
  survivalBuilding("workshop.roof", "structure-roof"),
  survivalProp("workshop.canvas", "structure-canvas", "workshop", 10),
  survivalProp("workshop.floor", "structure-floor", "workshop", 10),
  survivalProp("workshop.workbench", "workbench", "workshop", 10),
  survivalProp("workshop.anvil", "workbench-anvil", "workshop", 10),
  survivalProp("workshop.grinder", "workbench-grind", "workshop", 10),
  survivalBuilding("forge.structure", "structure-metal"),
  survivalBuilding("forge.roof", "structure-metal-roof"),
  survivalBuilding("forge.wall", "structure-metal-wall"),
  survivalProp("forge.doorway", "structure-metal-doorway", "workshop", 10),
  survivalProp("forge.floor", "structure-metal-floor", "workshop", 10),
  survivalBuilding("camp.tent", "tent", "village"),
  survivalProp("camp.tentCanvas", "tent-canvas", "village", 10),
  survivalProp("camp.fire", "campfire-pit", "village", 10),
  survivalProp("camp.fireStand", "campfire-stand", "village", 10),
  survivalProp("tool.hammer", "tool-hammer", "workshop", 10),
  survivalProp("workshop.planks", "resource-planks", "workshop", 10),
  survivalProp("workshop.stone", "resource-stone", "workshop", 10),
  survivalProp("workshop.wood", "resource-wood", "workshop", 10),
  survivalProp("workshop.barrel", "barrel", "village", 10),
  survivalProp("workshop.barrelOpen", "barrel-open", "village", 10),
  survivalProp("workshop.box", "box", "village", 10),
  survivalProp("workshop.chest", "chest", "village", 10),
  survivalProp("workshop.fence", "fence", "village", 10),
  survivalProp("workshop.signpost", "signpost-single", "village", 10),
  survivalProp("workshop.bucket", "bucket", "village", 10),
  survivalProp("workshop.boxLarge", "box-large", "village", 10),
  survivalProp("workshop.fenceFortified", "fence-fortified", "village", 10),

  // —— Castle keep / CoC-style defenses (no plot walls) ——
  castleModular("castle.towerSquare", "tower-square"),
  castleModular("castle.towerSquareBase", "tower-square-base"),
  castleModular("castle.towerSquareMidDoor", "tower-square-mid-door"),
  castleModular("castle.towerSquareMid", "tower-square-mid"),
  castleModular("castle.towerSquareTopRoofHigh", "tower-square-top-roof-high"),
  castleModular("castle.towerSquareTopRoofWindows", "tower-square-top-roof-high-windows"),
  castleModular("castle.towerSquareTopRoof", "tower-square-top-roof"),
  castleModular("castle.towerSquareArch", "tower-square-arch"),
  castleModular("castle.towerSquareTop", "tower-square-top"),
  castleModular("castle.wall", "wall"),
  castleModular("castle.wallCorner", "wall-corner"),
  castleModular("castle.wallCornerHalfTower", "wall-corner-half-tower"),
  castleModular("castle.wallHalf", "wall-half"),
  castleModular("castle.wallDoorway", "wall-doorway"),
  castleModular("castle.wallNarrowStairs", "wall-narrow-stairs"),
  castleModular("castle.towerHexagonBase", "tower-hexagon-base"),
  castleModular("castle.towerHexagonMid", "tower-hexagon-mid"),
  castleModular("castle.towerHexagonRoof", "tower-hexagon-roof"),
  castleModular("castle.towerHexagonTop", "tower-hexagon-top"),
  castleModular("castle.towerHexagonTopWood", "tower-hexagon-top-wood"),
  castleModular("castle.towerSlantRoof", "tower-slant-roof"),
  castleModular("castle.towerSquareMidWindows", "tower-square-mid-windows"),
  castleModular("castle.towerSquareMidOpen", "tower-square-mid-open"),
  castleModular("castle.stairsStone", "stairs-stone"),
  castleModular("castle.stairsSquare", "stairs-stone-square"),
  castleModular("castle.bridgeDraw", "bridge-draw"),
  castleProp("castle.flagBanner", "flag-banner-long"),
  castleProp("castle.flagBannerShort", "flag-banner-short"),
  castleProp("castle.flagPennant", "flag-pennant"),
  castleProp("castle.flagWide", "flag-wide"),
  castleProp("castle.flagPole", "flag"),
  castleProp("castle.gate", "gate"),
  castleProp("castle.metalGate", "metal-gate"),
  castleProp("castle.rocksSmall", "rocks-small"),
  castleProp("castle.rocksLarge", "rocks-large"),
  castleProp("castle.ballista", "siege-ballista"),
  castleProp("castle.catapult", "siege-catapult"),
  castleProp("castle.siegeRam", "siege-ram"),
  castleProp("castle.siegeTower", "siege-tower"),
  castleProp("castle.trebuchet", "siege-trebuchet"),
  castleProp("castle.treeLarge", "tree-large"),
  castleProp("castle.treeSmall", "tree-small"),
  castleProp("castle.treeLog", "tree-log"),
  castleProp("castle.door", "door"),

  // —— Retro Fantasy keep pieces (towers/roofs/props only — no curtain walls) ——
  retroFantasyModular("retro.towerPaintBase", "tower-paint-base"),
  retroFantasyModular("retro.towerPaint", "tower-paint"),
  retroFantasyModular("retro.roof", "roof"),
  retroFantasyModular("retro.roofHighSide", "roof-high-side"),
  retroFantasyModular("retro.overhang", "overhang"),
  retroFantasyModular("retro.overhangRound", "overhang-round"),
  retroFantasyModular("retro.columnWood", "column-wood"),
  retroFantasyModular("retro.stairsWood", "stairs-wood"),
  retroFantasyProp("retro.barrel", "detail-barrel"),
  retroFantasyProp("retro.crate", "detail-crate"),
  retroFantasyProp("retro.ladder", "ladder"),

  // —— Blocky villagers ——
  blockyCharacter("villager.a", "character-a"),
  blockyCharacter("villager.b", "character-b"),
  blockyCharacter("villager.c", "character-c"),
  blockyCharacter("villager.d", "character-d"),
  blockyCharacter("villager.e", "character-e"),
  blockyCharacter("villager.f", "character-f"),
  blockyCharacter("villager.g", "character-g"),
  blockyCharacter("villager.h", "character-h"),
  blockyCharacter("villager.i", "character-i"),
  blockyCharacter("villager.j", "character-j"),
  blockyCharacter("villager.k", "character-k"),
  blockyCharacter("villager.l", "character-l"),
  blockyCharacter("villager.m", "character-m"),
  blockyCharacter("villager.n", "character-n"),
  blockyCharacter("villager.o", "character-o"),
  blockyCharacter("villager.p", "character-p"),
  blockyCharacter("villager.q", "character-q"),
  blockyCharacter("villager.r", "character-r"),
];
